#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3  
bspc monitor DP-0 -d 4 5 6
bspc monitor DP-3 -d 7 8 9

bspc config border_width        3 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^2'
bspc rule -a ranger desktop='^3'
bspc rule -a firefox desktop='^4'
bspc rule -a steam desktop='^5'
bspc rule -a spotify desktop='^7'

~/.config/polybar/launch.sh
